// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0hIuRZ5lzkvC8ODg_omF2s6-OETlOFpI',
    appId: '1:567311743617:web:cc25164c13b699295dab80',
    messagingSenderId: '567311743617',
    projectId: 'chat-app-mobile-2025',
    authDomain: 'chat-app-mobile-2025.firebaseapp.com',
    storageBucket: 'chat-app-mobile-2025.firebasestorage.app',
    measurementId: 'G-Q17KBZS57D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8b9nNPmqqTJEKokFf7EUY9giw8XL-hVM',
    appId: '1:567311743617:android:0ace5407cc6558c65dab80',
    messagingSenderId: '567311743617',
    projectId: 'chat-app-mobile-2025',
    storageBucket: 'chat-app-mobile-2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUwY5PBslkhSkAsDAvKwDPHCLQdDXlhbo',
    appId: '1:567311743617:ios:6d19455850a9caf95dab80',
    messagingSenderId: '567311743617',
    projectId: 'chat-app-mobile-2025',
    storageBucket: 'chat-app-mobile-2025.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUwY5PBslkhSkAsDAvKwDPHCLQdDXlhbo',
    appId: '1:567311743617:ios:6d19455850a9caf95dab80',
    messagingSenderId: '567311743617',
    projectId: 'chat-app-mobile-2025',
    storageBucket: 'chat-app-mobile-2025.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0hIuRZ5lzkvC8ODg_omF2s6-OETlOFpI',
    appId: '1:567311743617:web:d5016dd657f984975dab80',
    messagingSenderId: '567311743617',
    projectId: 'chat-app-mobile-2025',
    authDomain: 'chat-app-mobile-2025.firebaseapp.com',
    storageBucket: 'chat-app-mobile-2025.firebasestorage.app',
    measurementId: 'G-TC1HKMMKTL',
  );
}
